# Generated by Django 4.2.29 on 2026-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('certificate', 'Course Certificate'), ('offer_letter', 'Offer Letter')], default='certificate', max_length=20)),
                ('issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated/certificates/')),
                ('role', models.CharField(blank=True, help_text='Role/position in offer letter', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('custom_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
