# Generated by Django 4.2.29 on 2026-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_level_course_rating_course_students_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligibility',
            field=models.CharField(blank=True, default='Any Branch', help_text='e.g. Any Branch, CSE/IT, ECE/EE, Mechanical', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('hinglish', 'Hinglish')], default='hinglish', help_text='Language course is taught in', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='next_batch_date',
            field=models.DateField(blank=True, help_text='Date of next batch starting', null=True),
        ),
    ]
