# Generated by Django 4.2.29 on 2026-03-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_type', models.CharField(choices=[('upload', 'Uploaded Video'), ('embed', 'Embed Link (YouTube/Vimeo)')], default='upload', max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lectures/videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('embed_code', models.TextField(blank=True, help_text='Optional custom embed HTML')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False, help_text='Free preview without enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='lectures.lecture')),
            ],
        ),
    ]
